version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Login to dockerhub
          command: ./papiea-engine/docker-login.py

      - run:
          name: Start service
          command: |
            cp .circleci/docker-compose.yml .
            cp .circleci/Dockerfile .
            docker-compose build
            docker-compose up -d

      - run:
          name: Waiting for service to be ready
          command: |
            for i in `seq 1 10`;
            do
              docker-compose logs --tail=5 server | grep 'app listening on port' && echo Success && exit 0
              sleep 15
              docker-compose logs --tail=5
            done
            echo Failed waiting for service && exit 1

      - run:
          name: Run unit tests
          command: |
            docker-compose exec server npm run test-ci
            docker cp project_server_1:/code/reports . || echo .
            docker cp project_server_1:/code/coverage . || echo .

      - run: ./papiea-engine/publish-images.py

      - run: docker-compose down

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports
          destination: reports

      - store_artifacts:
          path: coverage
          destination: coverage