version: 2.1
commands:
  run_tests:
    steps:
      - run:
          name: Login to dockerhub
          command: ./papiea-engine/docker-login.py

      - run:
          name: Start service
          command: |
            cp .circleci/docker-compose.yml .
            cp .circleci/Dockerfile .
            docker-compose build
            docker-compose up -d

      - run:
          name: Waiting for service to be ready
          command: |
            for i in `seq 1 10`;
            do
              docker-compose logs --tail=5 papiea-engine | grep 'app listening on port' && echo Success && exit 0
              sleep 15
              docker-compose logs --tail=5
            done
            echo Failed waiting for service && exit 1

      - run:
          name: Run unit tests
          command: |
            docker-compose exec papiea-engine npm run test-ci
            docker-compose exec papiea-engine bash -c 'cd /code/papiea-sdk/typescript && npm test'
            docker-compose exec papiea-engine bash -c 'cd /code/papiea-sdk/python/e2e_tests && python3.8 -m pip install -r requirements.txt && python3.8 -m pytest -s --disable-pytest-warnings'
            docker cp papiea-engine:/code/papiea-engine/reports . || echo .
            docker cp papiea-engine:/code/papiea-engine/coverage . || echo .
            docker cp papiea-engine:/code/papiea-engine/src/logs . || echo .

jobs:
  dev-build:
    docker:
      - image: circleci/node:10

    steps:
      - setup_remote_docker

      - checkout

      - run_tests

      - run: ./papiea-engine/publish-images.py

      - run: docker-compose down

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports
          destination: reports

      - store_artifacts:
          path: coverage
          destination: coverage
      
      - store_artifacts:
          path: logs
          destination: logs

  papiea-test:
    docker:
      - image: circleci/node:10

    steps:
      - setup_remote_docker

      - checkout

      - run_tests

      - run: docker-compose down

  release:
    docker:
      - image: circleci/node:10

    steps:
      - setup_remote_docker

      - add_ssh_keys:
          fingerprints:
            - "bb:51:bb:f8:5a:4e:94:dd:39:54:f7:2d:ea:be:b1:16"

      - checkout

      - run:
          name: Login to dockerhub
          command: ./papiea-engine/docker-login.py

      - run:
          name: Login to git as Updater Bot
          command: |
            git config user.email "<>"
            git config user.name "Version Updater Bot"

      - run: ./papiea-engine/npm-login.py

      - run: ./switch-registry.sh nutanix

      - run: ./upgrade-versions.sh -y

workflows:
  version: 2
  build-and-release:
    jobs:
      - papiea-test
#          filters:
#            branches:
#              only: master
      - release:
          requires:
            - papiea-test
#          filters:
#            branches:
#              only: master
#  build-development-version:
#    jobs:
#      - dev-build:
#          filters:
#            branches:
#              ignore: master
