version: '3.5'
services:
        papiea-engine:
                image: papiea-engine:debug
                container_name: papiea-engine
                build:
                        dockerfile: Dockerfile
                        target: debug
                        context: .
                environment:
                        - JEST_JUNIT_OUTPUT=reports/junit/results.xml
                depends_on:
                        - mongo
        mongo:
                image: mongo:4.1
