version: '3'
services:
        server:
                build:
                        dockerfile: Dockerfile
                        context: papiea-engine
                environment:
                        - JEST_JUNIT_OUTPUT=reports/junit/results.xml
                depends_on:
                        - mongo
        mongo:
                image: mongo:4.1