version: '3'
services:
        papiea-engine:
                container_name: papiea-engine
                build:
                        dockerfile: Dockerfile
                        target: builder
                        context: .
                environment:
                        - JEST_JUNIT_OUTPUT=reports/junit/results.xml
                depends_on:
                        - mongo
        mongo:
                image: mongo:4.1
