version: '3.5'
services:
        papiea-engine:
                container_name: papiea-engine-benchmark
                build: ../.
                image: nutanix-docker.jfrog.io/papiea:base
                volumes:
                        - ../../:/code
                ports:
                        - "3333:3000"
                environment:
                        - PAPIEA_ADMIN_S2S_KEY=${PAPIEA_ADMIN_S2S_KEY}
                        - PAPIEA_PUBLIC_URL=${PAPIEA_PUBLIC_URL}
                        - MONGO_URL=${MONGO_URL}
                        - HOT_RELOAD=${HOT_RELOAD:-false}
                        - LOGGING_LEVEL=${LOGGING_LEVEL:-info}