version: '3.5'
services:
        papiea-engine:
                container_name: papiea-engine
                build: .
                image: nutanix-docker.jfrog.io/papiea:base
                volumes:
                        - ../:/code
                depends_on:
                        - mongo
                ports:
                        - "3333:3000"
                environment:
                        - HOT_RELOAD=${HOT_RELOAD:-false}
        mongo:
                image: mongo:4.1